doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Infrastructure:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'App\Infrastructure\Doctrine\Entity'
                alias: Infrastructure

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
