security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$NWxIF60RcOXCC2dOx7nxKORFDnlIqRGyZYUrSlg/hLuwEjqDm6zMy' # "admin"
                        roles: ['ROLE_ADMIN']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            security: false
